spring:
  application:
    name: ride-share-api
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ride-share}
    username: ${SPRING_DATASOURCE_USERNAME:rideshare_user}
    password: ${SPRING_DATASOURCE_PASSWORD:rideshare_pass}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: ${SERVER_PORT:8080}
